users: # Register Users
  - name: Clara
    email: clara@domain.example
  - name: Tom
    email: tom@domain.example
  - name: Jonas
    email: jonas@domain.example
  - name: Max
    email: max@domain.example
  - name: Lena
    email: lena@domain.example
  - name: Leo
    email: leo@domain.example
  - name: Jan
    email: jan@domain.example

forbiddenCombinations: # Write down permitted combinations
  - combination:
      - Max    # Max can never get Lena
      - Lena   # Lena can never get Max
  - combination:
      - Jonas
      - Jan
  - combination:
      - Clara # Clara can never get Leo or Tom
      - Leo
      - Tom