users: # Register Users
  - name: Clara
    email: jonasbender2005@gmail.com
  - name: Tom
    email: jonasbender2005@gmail.com
  - name: Jonas
    email: jonasbender2005@gmail.com
  - name: Max
    email: jonasbender2005@gmail.com
  - name: Lena
    email: jonasbender2005@gmail.com
  - name: Leo
    email: jonasbender2005@gmail.com
  - name: Jan
    email: jonasbender2005@gmail.com

forbiddenCombinations: # Write down permitted combinations
  - combination:
      - Max    # Max can never get Lena
      - Lena   # Lena can never get Max
  - combination:
      - Jonas
      - Jan
  - combination:
      - Clara # Clara can never get Leo or Tom
      - Leo
      - Tom
emailConfig:
  subject: SecretSanta 2020
  content: Hi %v, your gift goes to %v  # The first %v is the mail receiver name and the second %v is the where the gift goes to