name: Create Release

on:
  create:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'SNAPSHOT')"
    outputs:
      version: ${{ steps.gen_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set values
        id: gen_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref }}
          name: ${{ steps.gen_version.outputs.VERSION }}
          body: |
            This is release ${{ steps.gen_version.outputs.VERSION }}
          draft: false
          prerelease: false
